# Training llama model for the 43% of the original model to match the superset tokenizer 
# use with apps/main/configs/flexitok/llama_1b_base.yaml
#  python -m lingua.stool nodes=2 script=apps.main.train config=["apps/main/configs/flexitok/llama_1b_base.yaml","apps/main/configs/ablations/2.11b_parity_aware_bpe_tr_500k_val_1000_2nodes.yaml"] 
#  python -m lingua.stool_ccdb ngpu=1 ncpu=1 launcher=bash script=apps.main.train config=["apps/main/configs/flexitok/llama_1b_base.yaml","apps/main/configs/ablations/2.11b_parity_aware_bpe_tr_500k_val_1000_2nodes.yaml"] 
dump_dir: /fsx/craffel/lingua_logs/parity_aware_bpe_tr_500k_val_1000_2_nodes
name: parity_aware_bpe_tr_500k_val_1000_2_nodes
grad_acc_steps: 4


data:
  tokenizer:
    name: huggingface
    path: flexitok/parity_aware_bpe_tr_500k_val_1000_2_nodes

checkpoint:
  init_ckpt_path: 
  path: /fsx/craffel/lingua_logs/checkpoints/parity_aware_bpe_tr_500k_val_1000_2_nodes/
  dump:
    every: 10000
    keep: -1
  eval:
    every: 10000
    keep: -1
