# Config for super vocab built from tokenizers: flexitok/bpe_arb_Arab_8000, flexitok/bpe_ces_Latn_8000, flexitok/reindexed-flexitok-bpe_ltr_cmn_Hani_8000_v2, flexitok/bpe_dan_Latn_8000, flexitok/bpe_deu_Latn_8000, flexitok/bpe_ell_Grek_8000, flexitok/bpe_fas_Arab_8000, flexitok/bpe_fra_Latn_8000, flexitok/bpe_fw_edu_8000, flexitok/bpe_hun_Latn_8000, flexitok/bpe_ind_Latn_8000, flexitok/bpe_ita_Latn_8000, flexitok/reindexed-flexitok-bpe_ltr_jpn_Jpan_8000_v2, flexitok/bpe_nld_Latn_8000, flexitok/bpe_pol_Latn_8000, flexitok/bpe_por_Latn_8000, flexitok/bpe_rus_Cyrl_8000, flexitok/bpe_spa_Latn_8000, flexitok/bpe_swe_Latn_8000, flexitok/reindexed-flexitok-bpe_ltr_tur_Latn_8000_v2, flexitok/bpe_vie_Latn_8000
## Training superset tokenizer with individual tokenizers trained on Fineweb-2-hq
# use with apps/main/configs/flexitok/llama_1b_base.yaml
##TODO: add router details, make sure name is correct
# python -m lingua.stool script=apps.main.train config=[/fsx/craffel/lingua/apps/main/configs/flexitok/llama_1b_base.yaml,apps/main/configs/ablations/safe_oracle.yaml]
# python -m lingua.stool_ccdb ngpu=1 ncpu=1 nodes=1 launcher=bash script=apps.main.train config=[apps/main/configs/flexitok/llama_1b_base.yaml,apps/main/configs/ablations/safe_oracle.yaml]

model:
  vocab_size: 122554
  # dim: 128
name: safe
dump_dir: /fsx/craffel/lingua_logs/safe
data:
  tokenizer:
    name: supertokenizer
    seed: 42
    superset_code_name: safe
    n_words: 122554
    tokenizers:
    - name: huggingface
      path: flexitok/bpe_arb_Arab_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_ces_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/reindexed-flexitok-bpe_ltr_cmn_Hani_8000_v2
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_dan_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_deu_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_ell_Grek_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_fas_Arab_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_fra_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_fw_edu_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_hun_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_ind_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_ita_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/reindexed-flexitok-bpe_ltr_jpn_Jpan_8000_v2
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_nld_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_pol_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_por_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_rus_Cyrl_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_spa_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_swe_Latn_8000
      load_supermapping: false
    - name: huggingface
      path: flexitok/reindexed-flexitok-bpe_ltr_tur_Latn_8000_v2
      load_supermapping: false
    - name: huggingface
      path: flexitok/bpe_vie_Latn_8000
      load_supermapping: false
  routing:
    suitable_tokenizer_probability: 1.0
    source_to_tokenizer:
      arb_Arab: flexitok/bpe_arb_Arab_8000
      ces_Latn: flexitok/bpe_ces_Latn_8000
      cmn_Hani: flexitok/reindexed-flexitok-bpe_ltr_cmn_Hani_8000
      dan_Latn: flexitok/bpe_dan_Latn_8000
      deu_Latn: flexitok/bpe_deu_Latn_8000
      ell_Grek: flexitok/bpe_ell_Grek_8000
      fas_Arab: flexitok/bpe_fas_Arab_8000
      fra_Latn: flexitok/bpe_fra_Latn_8000
      fw_edu: flexitok/bpe_fw_edu_8000
      hun_Latn: flexitok/bpe_hun_Latn_8000
      ind_Latn: flexitok/bpe_ind_Latn_8000
      ita_Latn: flexitok/bpe_ita_Latn_8000
      jpn_Jpan: flexitok/reindexed-flexitok-bpe_ltr_jpn_Jpan_8000_v2
      nld_Latn: flexitok/bpe_nld_Latn_8000
      pol_Latn: flexitok/bpe_pol_Latn_8000
      por_Latn: flexitok/bpe_por_Latn_8000
      rus_Cyrl: flexitok/bpe_rus_Cyrl_8000
      spa_Latn: flexitok/bpe_spa_Latn_8000
      swe_Latn: flexitok/bpe_swe_Latn_8000
      tur_Latn: flexitok/reindexed-flexitok-bpe_ltr_tur_Latn_8000_v2
      vie_Latn: flexitok/bpe_vie_Latn_8000
checkpoint:
  path: /fsx/craffel/lingua_logs/checkpoints/safe
