data:
  root_dir: /u/gsaltintas/data
  sources:
    tur_Latn: 1.
    fineweb_edu_10bt_shuffled8: 0.

  tokenizer:
    name: tiktoken
    path: /u/gsaltintas/data/tokenizer/llama-3.2-1B/original/tokenizer.model
