# use with apps/main/configs/flexitok/llama_1b_base.yaml
#  python -m lingua.stool script=apps.main.train config=["/fsx/craffel/lingua/apps/main/configs/flexitok/llama_1b_base.yaml","/fsx/craffel/lingua/apps/main/configs/flexitok/llama_43k.yaml"] 
# Training llama model for the 43% of the original model to match the superset tokenizer 
dump_dir: /fsx/craffel/lingua_logs/llama_43k
name: llama_43k
steps: 43432
