# use with apps/main/configs/flexitok/llama_1b_base.yaml, apps/main/configs/flexitok/superset_tokenizer.yaml
# python -m lingua.stool script=apps.main.train config=["/fsx/craffel/lingua/apps/main/configs/flexitok/llama_1b_base.yaml","apps/main/configs/flexitok/superset_tokenizer.yaml","apps/main/configs/flexitok/superset_albert_w_xglm.yaml"]

dump_dir: /fsx/craffel/lingua_logs/flexitok_superset_albert_w_xglm
name: flexitok_superset_albert_w_xglm

model:
  use_factorized_embeddings: True
  factorized_embedding_dim: 512


data:
  tokenizer:
    name: supertokenizer
    seed: 42
    tokenizers:
      - name: huggingface
        # path: CohereLabs/aya-expanse-8b
        path: flexitok/reindexed-CohereLabs-aya-expanse-8b
        load_supermapping: False
      - name: huggingface
        path: flexitok/reindexed-bigscience-bloom
        # path: bigscience/bloom
        load_supermapping: False
      - name: huggingface
        # path: common-pile/comma-v0.1
        path: flexitok/reindexed-common-pile-comma-v0.1
        load_supermapping: False
      - name: huggingface
        # path: google/gemma-2-2b
        path: flexitok/reindexed-google-gemma-2-2b
        load_supermapping: False
      - name: huggingface
        # path: gpt2
        path: flexitok/reindexed-gpt2
        load_supermapping: False
      - name: huggingface
        # path: meta-llama/Llama-3.2-1B
        path: flexitok/reindexed-meta-llama-Llama-3.2-1B
        load_supermapping: False
      - name: huggingface
        # path: google-bert/bert-base-multilingual-cased
        path: flexitok/reindexed-google-bert-bert-base-multilingual-cased
        load_supermapping: False
      - name: huggingface
        # path: microsoft/Phi-3-mini-4k-instruct
        path: flexitok/reindexed-microsoft-Phi-3-mini-4k-instruct
        load_supermapping: False
      - name: huggingface
        # path: Qwen/Qwen3-8B
        path: flexitok/reindexed-Qwen-Qwen3-8B
        load_supermapping: False
      - name: huggingface
        path: facebook/xglm-564M
        # path: flexitok/reindexed-facebook-xglm-564M
        load_supermapping: True
      - name: huggingface
        path: google/byt5-small
        load_supermapping: True
      - name: tiktoken
        path: gpt-4o
        load_supermapping: True
      - name: tekken
        path: tekken
        load_supermapping: True
      - name: tokenmonster
        path: englishcode-32000-consistent-v1
        load_supermapping: True
