# Copyright (c) R3 Lab.
# Modified stool.py for AMD MI300X with torchrun

import json
import os
import shutil
import subprocess
from dataclasses import dataclass
from typing import Any, Dict, MutableSequence

from omegaconf import OmegaConf

from lingua.args import dataclass_from_dict


@dataclass
class AMDToolArgs:
    config: Any = None
    launcher: str = "bash"  # bash or torchrun
    script: str = "apps.main.train"  # The script to run.
    copy_code: bool = True  # Whether to copy code to dump dir
    dirs_exists_ok: bool = True  # Whether to copy new code and config and run regardless that dir exists
    override: bool = False  # Whether to delete dump dir and restart
    nodes: int = 1  # The number of nodes to run the job on.
    ngpu: int = 1  # The number of GPUs required per node.
    ncpu: int = 16  # The number of CPUs allocated per task.
    mem: str = ""  # The amount of memory to allocate (not enforced without SLURM).
    anaconda: str = "default"  # The path to the anaconda environment.
    master_addr: str = "127.0.0.1"  # Master address for distributed training
    master_port: int = 29501  # Master port for rendezvous
    rocm_home: str = "/opt/rocm"  # Path to ROCm installation
    stdout: bool = False  # Whether to output to stdout or log files
    data_dir: str = "/data/lingua/"  # Local data directory


TORCHRUN_SCRIPT = """#!/bin/bash

# AMD MI300X Training Script
# Generated by amdtool.py

PROJECT_FOLDER={dump_dir}/code

cd $PROJECT_FOLDER
source activate {conda_env_path}

# --------------------------------------------------------
# AMD MI300X Configuration
# --------------------------------------------------------
export ROCM_HOME={rocm_home}
export HSA_OVERRIDE_GFX_VERSION=9.4.2

export CUDA_VISIBLE_DEVICES={gpu_ids}
export HIP_VISIBLE_DEVICES={gpu_ids}

# --------------------------------------------------------
# Force IPv4 for all network operations
# --------------------------------------------------------
export NCCL_SOCKET_FAMILY=AF_INET
export GLOO_SOCKET_FAMILY=AF_INET

# --------------------------------------------------------
# Cache Directories
# --------------------------------------------------------
export TIKTOKEN_CACHE_DIR="$HOME/.cache/tiktoken"
export HF_HOME="$HOME/.cache/huggingface"
export HF_HUB_CACHE="$HOME/.cache/huggingface/hub"
export HF_HUB_CACHE_DIR="$HOME/.cache/huggingface/hub"

# --------------------------------------------------------
# RCCL Configuration
# --------------------------------------------------------
export NCCL_TIMEOUT=3600
export NCCL_BLOCKING_WAIT=1
export NCCL_ASYNC_ERROR_HANDLING=1
export NCCL_SOCKET_IFNAME=lo
export GLOO_SOCKET_IFNAME=lo
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=0
export NCCL_SHM_DISABLE=0

# Debugging (reduce to WARN for production)
export NCCL_DEBUG=INFO
export TORCH_DISTRIBUTED_DEBUG=DETAIL

# --------------------------------------------------------
# wandb Configuration
# --------------------------------------------------------
# export WANDB_MODE=offline 
export WANDB_DIR="{dump_dir}/wandb"

# --------------------------------------------------------
# Environment
# --------------------------------------------------------
export OMP_NUM_THREADS=1
export DUMP_DIR={dump_dir}
export TMPDIR=/tmp

# --------------------------------------------------------
# Distributed Training Parameters
# --------------------------------------------------------
MASTER_ADDR={master_addr}
MASTER_PORT={master_port}
RDZV_ID={rdzv_id}
NPROC_PER_NODE={ngpu}
NNODES={nodes}

echo "=========================================="
echo "Training Configuration"
echo "=========================================="
echo "Master Address: $MASTER_ADDR"
echo "Master Port: $MASTER_PORT"
echo "Rendezvous ID: $RDZV_ID"
echo "GPUs per node: $NPROC_PER_NODE"
echo "Number of nodes: $NNODES"
echo "Dump directory: $DUMP_DIR"
echo "=========================================="

# Test GPU availability
echo "Testing GPU availability..."
python -c "import torch; print(f'CUDA available: {{torch.cuda.is_available()}}'); print(f'Device count: {{torch.cuda.device_count()}}')"

# Test tiktoken cache
echo "Testing tiktoken..."
python -c "import tiktoken; tiktoken.encoding_for_model('gpt-4o')" 2>/dev/null || echo "Tiktoken test skipped"

{copy_data_command}

echo "=========================================="
echo "Starting training..."
echo "=========================================="

{log_redirect}torchrun \\
    --nproc-per-node=$NPROC_PER_NODE \\
    --nnodes=$NNODES \\
    --node-rank={node_rank} \\
    --master-addr=$MASTER_ADDR \\
    --master-port=$MASTER_PORT \\
    --rdzv_id=$RDZV_ID \\
    --rdzv_backend=static \\
    --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \\
    --max_restarts=0 \\
    --log_dir={dump_dir}/logs \\
    -m {script} \\
    config=$DUMP_DIR/base_config.yaml{log_suffix}
"""


def copy_dir(input_dir: str, output_dir: str) -> None:
    print(f"Copying : {input_dir}\n" f"to      : {output_dir} ...")
    assert os.path.isdir(input_dir), f"{input_dir} is not a directory"
    assert os.path.isdir(output_dir), f"{output_dir} is not a directory"
    rsync_cmd = (
        f"rsync -arm --copy-links "
        f"--include '**/' "
        f"--include '*.py' "
        f"--exclude='*' "
        f"{input_dir}/ {output_dir}"
    )
    print(f"Copying command: {rsync_cmd}")
    subprocess.call([rsync_cmd], shell=True)
    print("Copy done.")


def validate_args(args) -> None:
    if hasattr(args, "anaconda") and args.anaconda:
        if args.anaconda == "default":
            args.anaconda = (
                subprocess.check_output("which python", shell=True)
                .decode("ascii")
                .strip()
            )
        else:
            args.anaconda = f"{args.anaconda}/bin/python"
        assert os.path.isfile(args.anaconda), f"Python not found at {args.anaconda}"

    args.mem = args.mem or "0"

    assert args.ngpu > 0, "Number of GPUs must be positive"
    assert args.ncpu > 0, "Number of CPUs must be positive"
    assert args.nodes > 0, "Number of nodes must be positive"
    assert os.path.isdir(args.rocm_home), f"ROCm not found at {args.rocm_home}"


def launch_job(args: AMDToolArgs):
    # Set up args default and validate them
    validate_args(args)
    dump_dir = args.config["dump_dir"]
    job_name = args.config["name"]

    # Prepare data copy commands
    copy_data_command = ""
    if "data" in args.config:
        data_dir = args.data_dir
        data_root_dir = args.config["data"]["root_dir"]
        data_sources = args.config["data"]["sources"]
        
        for source in data_sources.keys():
            copy_data_command += f"echo 'Copying data for {source}...'\n"
            copy_data_command += f"mkdir -p {data_root_dir}/{source}\n"
            if os.path.exists(f"{data_dir}/{source}"):
                copy_data_command += f"rsync -arm -v --stats --progress {data_dir}/{source}/ {data_root_dir}/{source}/\n"
            else:
                copy_data_command += f"echo 'Warning: Source {data_dir}/{source} not found, skipping...'\n"

    print("Creating directories...")
    os.makedirs(dump_dir, exist_ok=args.dirs_exists_ok or args.override)
    if args.override:
        confirm = input(
            f"Are you sure you want to delete the directory '{dump_dir}'? This action cannot be undone. (yes/no): "
        )
        if confirm.lower() == "yes":
            shutil.rmtree(dump_dir)
            os.makedirs(dump_dir)
            print(f"Directory '{dump_dir}' has been deleted and recreated.")
        else:
            print("Operation cancelled.")
            return
    
    os.makedirs(os.path.join(dump_dir, "logs"), exist_ok=args.dirs_exists_ok)
    os.makedirs(os.path.join(dump_dir, "wandb"), exist_ok=args.dirs_exists_ok)
    
    if args.copy_code:
        os.makedirs(f"{dump_dir}/code", exist_ok=args.dirs_exists_ok)
        print("Copying code ...")
        copy_dir(os.getcwd(), f"{dump_dir}/code")

    print("Saving config file ...")
    with open(f"{dump_dir}/base_config.yaml", "w") as cfg:
        cfg.write(OmegaConf.to_yaml(args.config))

    # Setup environment paths
    conda_env_path = os.path.dirname(os.path.dirname(args.anaconda))
    
    # GPU IDs (e.g., "0" for single GPU, "0,1,2,3" for 4 GPUs)
    gpu_ids = ",".join(str(i) for i in range(args.ngpu))
    
    # Rendezvous ID (use a random number for multi-run isolation)
    import random
    rdzv_id = random.randint(100000, 999999)
    
    # Log redirection
    if args.stdout:
        log_redirect = ""
        log_suffix = ""
    else:
        timestamp = "$(date +%Y%m%d_%H%M%S)"
        log_redirect = ""
        log_suffix = f" > {dump_dir}/logs/train_{timestamp}.log 2>&1"
    
    # Generate launch script for single node (node_rank=0)
    launch_script = TORCHRUN_SCRIPT.format(
        dump_dir=dump_dir,
        conda_env_path=conda_env_path,
        rocm_home=args.rocm_home,
        gpu_ids=gpu_ids,
        master_addr=args.master_addr,
        master_port=args.master_port,
        rdzv_id=rdzv_id,
        ngpu=args.ngpu,
        nodes=args.nodes,
        node_rank=0,  # For single node, always 0
        script=args.script,
        copy_data_command=copy_data_command,
        log_redirect=log_redirect,
        log_suffix=log_suffix,
    )

    print("Writing launch script ...")
    script_path = f"{dump_dir}/launch.sh"
    with open(script_path, "w") as f:
        f.write(launch_script)
    
    # Make script executable
    os.chmod(script_path, 0o755)

    if args.nodes > 1:
        print("\n" + "="*60)
        print("MULTI-NODE SETUP INSTRUCTIONS")
        print("="*60)
        print(f"\nYou specified {args.nodes} nodes. To run multi-node training:")
        print(f"\n1. On the MASTER node (rank 0):")
        print(f"   bash {script_path}")
        print(f"\n2. On each WORKER node (rank 1, 2, ...):")
        print(f"   Edit {script_path} and change:")
        print(f"   --node-rank=0  -->  --node-rank=<worker_rank>")
        print(f"   --master-addr={args.master_addr}  -->  --master-addr=<master_ip>")
        print(f"\n3. Ensure all nodes can communicate on port {args.master_port}")
        print(f"\n4. Update NCCL_SOCKET_IFNAME to your network interface (e.g., ib0, eth0)")
        print("="*60 + "\n")
    else:
        print(f"\nLaunching single-node training on {args.ngpu} GPU(s)...")
        if args.launcher == "bash":
            os.system(f"bash {script_path}")
        else:
            print(f"Script ready at: {script_path}")
            print(f"Run with: bash {script_path}")

    print("Done.")


if __name__ == "__main__":
    """
    The command line interface here uses OmegaConf https://omegaconf.readthedocs.io/en/2.3_branch/usage.html#from-command-line-arguments
    This accepts arguments as a dot list
    
    Example usage:
        python amdtool.py config=configs/my_config.yaml ngpu=4 nodes=1
        python amdtool.py config=configs/my_config.yaml ngpu=8 nodes=2 master_addr=192.168.1.100
    """
    args = OmegaConf.from_cli()
    if isinstance(args.config, MutableSequence):
        args.config = OmegaConf.merge(*[OmegaConf.load(c) for c in args.config])
    else:
        args.config = OmegaConf.load(args.config)
    args = dataclass_from_dict(AMDToolArgs, args)
    launch_job(args)