name: mod_arith_mod-tokenizers-individual
dump_dir: /fsx/craffel/lingua_logs/modular_arithmetic/mod-tokenizers-individual

data:
  tokenizer:
    path: huggingface
    name: flexitok/mod-tokenizers-individual

logging:
  wandb:
    group: modular-arithmetic-ablations-corrected
    name: mod-tokenizers-individual

