# use with apps/main/configs/modular_arithmetic/base.yaml
# python -m lingua.stool_ccdb ngpu=1 ncpu=4 mem=64G time=800 nodes=1 gpu_type=l40s launcher=bash script=apps.main.train_answer_only config=["apps/main/configs/modular_arithmetic/base.yaml","apps/main/configs/modular_arithmetic/modular_artihmetic_superset.yaml"]
# python -m lingua.stool_ccdb ngpu=1 ncpu=4 mem=64G time=800 nodes=1 gpu_type=l40s launcher=sbatch script=apps.main.train_answer_only config=["apps/main/configs/modular_arithmetic/base.yaml","apps/main/configs/modular_arithmetic/modular_artihmetic_superset.yaml"]
dump_dir: /fsx/craffel/lingua_logs/flexitok_superset_mod_tokenizers
name: flexitok_superset_mod_tokenizers

model:
  vocab_size: 100007

data:
  tokenizer:
    name: supertokenizer
    seed: 42
    superset_code_name: mod_tokenizers
    n_words: 100007

    tokenizers:
      - name: huggingface
        path: flexitok/mod-tokenizers-individual
        load_supermapping: True
      - name: huggingface
        path: flexitok/mod-tokenizers-ltr_3digit
        load_supermapping: True
      - name: huggingface
        path: flexitok/mod-tokenizers-ltr_2digit
        load_supermapping: True
      - name: huggingface
        path: flexitok/mod-tokenizers-ltr_4digit
        load_supermapping: True
      - name: huggingface
        path: flexitok/mod-tokenizers-ltr_5digit
        load_supermapping: True
      - name: huggingface
        path: flexitok/mod-tokenizers-rtl_2digit
        load_supermapping: True
      - name: huggingface
        path: flexitok/mod-tokenizers-rtl_3digit
        load_supermapping: True
      - name: huggingface
        path: flexitok/mod-tokenizers-rtl_4digit
        load_supermapping: True
