# use with apps/main/configs/moto/base.yaml
dump_dir: /fsx/craffel/lingua_logs/flexitok_llama_bpe_dropout


data:
  tokenizer:
    name: huggingface
    path: meta-llama/Llama-3.2-1B
    dropout: 0.1
