# python -m lingua.stool_ccdb ngpu=1 ncpu=1 mem=64G time=800 nodes=1 gpu_type=l40s launcher=sbatch script=apps.main.eval config=["apps/main/configs/flexitok/eval/eval_base.yaml",apps/main/configs/flexitok/eval/2.4-eval-llama-albert.yaml]

name: flexitok_llama_albert
dump_dir: /fsx/craffel/lingua_logs/flexitok_llama_albert/eval/
ckpt_dir: /fsx/craffel/lingua_logs/flexitok_llama_albert/checkpoints/0000100000/

wandb:
  name: Llama-Albert

tokenizer:
  name: huggingface
  path: meta-llama/Llama-3.2-1B
