# python -m lingua.stool_ccdb ngpu=1 ncpu=1 mem=64G time=800 nodes=1 gpu_type=l40s launcher=sbatch script=apps.main.eval config=["apps/main/configs/flexitok/eval/eval_base.yaml",apps/main/configs/flexitok/eval/2.7.3-eval-llama_and16k-oracle.yaml]
name: fw2hq_llama_and_16k_oracle
dump_dir: /fsx/craffel/lingua_logs/llama_and_16k/eval
ckpt_dir: /fsx/craffel/lingua_logs/llama_and_16k/checkpoints/0000100000/

wandb:
  name: FW2HQ-Llama-16K-Oracle

routing:
  suitable_tokenizer_probability: 1.0
  task_to_tokenizer:
    arc_easy: flexitok/llama-3.2-1b-tokenizer
    arc_challenge: flexitok/llama-3.2-1b-tokenizer
    hellaswag: flexitok/llama-3.2-1b-tokenizer
    piqa: flexitok/llama-3.2-1b-tokenizer

    # --- MMLU / Base 44 ---
    regex:include_base_44_arabic*: flexitok/bpe_ltr_arb_Arab_16000_v2
    # no czech, swedish, danish
    regex:include_base_44_chinese*: flexitok/bpe_ltr_cmn_Hani_16000_v2
    regex:include_base_44_german*: flexitok/bpe_ltr_deu_Latn_16000_v2
    regex:include_base_44_greek*: flexitok/bpe_ltr_ell_Grek_16000_v2
    regex:include_base_44_persian*: flexitok/bpe_ltr_fas_Arab_16000_v2
    regex:include_base_44_french*: flexitok/bpe_ltr_fra_Latn_16000_v2
    regex:include_base_44_hungarian*: flexitok/bpe_ltr_hun_Latn_16000_v2
    regex:include_base_44_indonesian*: flexitok/bpe_ltr_ind_Latn_16000_v2
    regex:include_base_44_italian*: flexitok/bpe_ltr_ita_Latn_16000_v2
    regex:include_base_44_japanese*: flexitok/bpe_ltr_jpn_Jpan_16000_v2
    regex:include_base_44_dutch*: flexitok/bpe_ltr_nld_Latn_16000_v2
    regex:include_base_44_polish*: flexitok/bpe_ltr_pol_Latn_16000_v2
    regex:include_base_44_portuguese*: flexitok/bpe_ltr_por_Latn_16000_v2
    regex:include_base_44_russian*: flexitok/bpe_ltr_rus_Cyrl_16000_v2
    regex:include_base_44_spanish*: flexitok/bpe_ltr_spa_Latn_16000_v2
    regex:include_base_44_turkish*: flexitok/bpe_ltr_tur_Latn_16000_v2
    regex:include_base_44_vietnamese*: flexitok/bpe_ltr_vie_Latn_16000_v2

    # --- Belebele ---
    belebele_arb_Arab: flexitok/bpe_ltr_arb_Arab_16000_v2
    belebele_ces_Latn: flexitok/bpe_ltr_ces_Latn_16000_v2
    belebele_zho_Hans: flexitok/bpe_ltr_cmn_Hani_16000_v2
    belebele_dan_Latn: flexitok/bpe_ltr_dan_Latn_16000_v2
    belebele_deu_Latn: flexitok/bpe_ltr_deu_Latn_16000_v2
    belebele_ell_Grek: flexitok/bpe_ltr_ell_Grek_16000_v2
    belebele_pes_Arab: flexitok/bpe_ltr_fas_Arab_16000_v2
    belebele_fra_Latn: flexitok/bpe_ltr_fra_Latn_16000_v2
    belebele_hun_Latn: flexitok/bpe_ltr_hun_Latn_16000_v2
    belebele_ind_Latn: flexitok/bpe_ltr_ind_Latn_16000_v2
    belebele_ita_Latn: flexitok/bpe_ltr_ita_Latn_16000_v2
    belebele_jpn_Jpan: flexitok/bpe_ltr_jpn_Jpan_16000_v2
    belebele_nld_Latn: flexitok/bpe_ltr_nld_Latn_16000_v2
    belebele_pol_Latn: flexitok/bpe_ltr_pol_Latn_16000_v2
    belebele_por_Latn: flexitok/bpe_ltr_por_Latn_16000_v2
    belebele_rus_Cyrl: flexitok/bpe_ltr_rus_Cyrl_16000_v2
    belebele_spa_Latn: flexitok/bpe_ltr_spa_Latn_16000_v2
    belebele_swe_Latn: flexitok/bpe_ltr_swe_Latn_16000_v2
    belebele_tur_Latn: flexitok/bpe_ltr_tur_Latn_16000_v2
    belebele_vie_Latn: flexitok/bpe_ltr_vie_Latn_16000_v2
    belebele_eng_Latn: flexitok/llama-3.2-1b-tokenizer

    # --- XNLI ---
    xnli_ar: flexitok/bpe_ltr_arb_Arab_16000_v2
    xnli_zh: flexitok/bpe_ltr_cmn_Hani_16000_v2
    xnli_de: flexitok/bpe_ltr_deu_Latn_16000_v2
    xnli_el: flexitok/bpe_ltr_ell_Grek_16000_v2
    xnli_en: flexitok/llama-3.2-1b-tokenizer
    xnli_es: flexitok/bpe_ltr_spa_Latn_16000_v2
    xnli_fr: flexitok/bpe_ltr_fra_Latn_16000_v2
    xnli_ru: flexitok/bpe_ltr_rus_Cyrl_16000_v2
    xnli_tr: flexitok/bpe_ltr_tur_Latn_16000_v2
    xnli_vi: flexitok/bpe_ltr_vie_Latn_16000_v2
    regex:toksuite_turkish*: flexitok/bpe_ltr_tur_Latn_16000_v2
    regex:toksuite_english*: flexitok/llama-3.2-1b-tokenizer
    regex:toksuite_farsi*: flexitok/bpe_ltr_fas_Arab_16000_v2
    regex:toksuite_italian*: flexitok/bpe_ltr_ita_Latn_16000_v2
    regex:toksuite_chinese*: flexitok/bpe_ltr_cmn_Hani_16000_v2
    regex:toksuite_math*: flexitok/llama-3.2-1b-tokenizer
    regex:toksuite_stem*: flexitok/llama-3.2-1b-tokenizer

    # flores
    flores200_arb_Arab: flexitok/bpe_ltr_arb_Arab_16000_v2
    flores200_ces_Latn: flexitok/bpe_ltr_ces_Latn_16000_v2
    flores200_cmn_Hani: flexitok/bpe_ltr_cmn_Hani_16000_v2
    flores200_dan_Latn: flexitok/bpe_ltr_dan_Latn_16000_v2
    flores200_deu_Latn: flexitok/bpe_ltr_deu_Latn_16000_v2
    flores200_ell_Grek: flexitok/bpe_ltr_ell_Grek_16000_v2
    flores200_fas_Arab: flexitok/bpe_ltr_fas_Arab_16000_v2
    flores200_fra_Latn: flexitok/bpe_ltr_fra_Latn_16000_v2
    flores200_fw_edu  : flexitok/llama-3.2-1b-tokenizer
    flores200_eng_Latn  : flexitok/llama-3.2-1b-tokenizer
    flores200_hun_Latn: flexitok/bpe_ltr_hun_Latn_16000_v2
    flores200_ind_Latn: flexitok/bpe_ltr_ind_Latn_16000_v2
    flores200_ita_Latn: flexitok/bpe_ltr_ita_Latn_16000_v2
    flores200_jpn_Jpan: flexitok/bpe_ltr_jpn_Jpan_16000_v2
    flores200_nld_Latn: flexitok/bpe_ltr_nld_Latn_16000_v2
    flores200_pol_Latn: flexitok/bpe_ltr_pol_Latn_16000_v2
    flores200_por_Latn: flexitok/bpe_ltr_por_Latn_16000_v2
    flores200_rus_Cyrl: flexitok/bpe_ltr_rus_Cyrl_16000_v2
    flores200_spa_Latn: flexitok/bpe_ltr_spa_Latn_16000_v2
    flores200_swe_Latn: flexitok/bpe_ltr_swe_Latn_16000_v2
    flores200_tur_Latn: flexitok/bpe_ltr_tur_Latn_16000_v2
    flores200_vie_Latn: flexitok/bpe_ltr_vie_Latn_16000_v2